
all: RandomNumberGenerator DataPoint DataGrabber	

RandomNumberGenerator:
	g++ -Wall -c RandomNumberGenerator.cpp -o NumberGenerator.o -std=c++11
	
DataPoint:
	g++ -Wall -c DataPoint.cpp -o DataPoint.o -std=c++11
	
DataGrabber:
	g++ -Wall -c DataGrabber.cpp -o DataGrabber.o -std=c++11
	
